### PR TITLE
format as properties

### PR DESCRIPTION
**Pull request by christian-fei**
Would like to know what you think. It looks a little bit cleaner to me.

Great job

### CODE REVIEW

**Comment by henrik** [comment]
Hey! Good thinking. This makes perfect sense.

The trailing commas on the last elements of the keyword lists are actually intentional. By not special-casing the last line, you can move lines around without accidental errors and diffs are slightly cleaner.

I'll merge this and make some small tweaks like that in a separate commit.

Thank you! :)

**Comment by christian-fei** [comment]
Good point on moving the lines around and cleaner diffs, I like that! :D

**Comment by christian-fei** [comment]
Just noticed that I concatenate two times (needlessly) in `format_spinners/2`
Hurried a bit too much in this PR

**Comment by henrik** [comment]
No worries, I changed that in the next commit: https://github.com/henrik/sipper/commit/7065f925611299b122df64418eb43e759d70f969

**Comment by christian-fei** [comment]
:+1:

**Pull request merged**
